# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tuip < Formula
  desc "Terminal CLI and TUI for checking public SaaS status pages"
  homepage "https://github.com/ikan31/tuip"
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ikan31/tuip/releases/download/v1.0.5/tuip_1.0.5_Darwin_x86_64.tar.gz"
      sha256 "498daf5261553a9bf1cb70ab049f202b830642be0bf2db3e5647f5cc710e7f22"

      define_method(:install) do
        bin.install "tuip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ikan31/tuip/releases/download/v1.0.5/tuip_1.0.5_Darwin_arm64.tar.gz"
      sha256 "b55fc2590200815a10659eb46c23923d4f53eb27e7294844a795c45213ea6a48"

      define_method(:install) do
        bin.install "tuip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ikan31/tuip/releases/download/v1.0.5/tuip_1.0.5_Linux_x86_64.tar.gz"
      sha256 "9a5d21d25c9ea503385152053740f40171e1b155210fa33847c57f83fd6b3017"
      define_method(:install) do
        bin.install "tuip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ikan31/tuip/releases/download/v1.0.5/tuip_1.0.5_Linux_arm64.tar.gz"
      sha256 "3e93f02d0ee2419c4aa4c619855ccf8a6213644ee0ea6ced44e52c49c9cdc953"
      define_method(:install) do
        bin.install "tuip"
      end
    end
  end

  test do
    system "#{bin}/tuip", "--version"
  end
end
