# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tuip < Formula
  desc "Terminal CLI and TUI for checking public SaaS status pages"
  homepage "https://github.com/ikan31/tuip"
  version "1.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ikan31/tuip/releases/download/v1.0.6/tuip_1.0.6_Darwin_x86_64.tar.gz"
      sha256 "deb19adffd072b8eaad7956910c4a1145dcbbc569d2697593012f274c923c4db"

      define_method(:install) do
        bin.install "tuip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ikan31/tuip/releases/download/v1.0.6/tuip_1.0.6_Darwin_arm64.tar.gz"
      sha256 "c2bb0829c3648e1c7fa5220fe5bbb7b2027884c5bec4cc1f298727bc37fd664b"

      define_method(:install) do
        bin.install "tuip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ikan31/tuip/releases/download/v1.0.6/tuip_1.0.6_Linux_x86_64.tar.gz"
      sha256 "c21e303506972fb9dbcd253bc37548f0ebc95d0f580e4288f15c0fd824634b71"
      define_method(:install) do
        bin.install "tuip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ikan31/tuip/releases/download/v1.0.6/tuip_1.0.6_Linux_arm64.tar.gz"
      sha256 "a4335b28a6cd037e0e9ab7a3edb545cb86b37dd2c8a56b6c4f25e5c6bac96f7b"
      define_method(:install) do
        bin.install "tuip"
      end
    end
  end

  test do
    system "#{bin}/tuip", "--version"
  end
end
